-- 018: No-op after removing MiniApp chat credit billing.
--
-- Earlier drafts used this migration for free-chat request idempotency. The
-- MiniApp no longer keeps credit-deduction database objects, so this migration
-- intentionally performs no schema changes.
