import { z } from 'zod';

export const BridgeErrorCodes = {
  BRIDGE_PROTOCOL_VERSION_MISMATCH: 'BRIDGE_PROTOCOL_VERSION_MISMATCH',
  BRIDGE_PROTOCOL_INVALID_ENVELOPE: 'BRIDGE_PROTOCOL_INVALID_ENVELOPE',
  BRIDGE_PROTOCOL_PAYLOAD_SCHEMA_INVALID: 'BRIDGE_PROTOCOL_PAYLOAD_SCHEMA_INVALID',
  BRIDGE_PROTOCOL_MESSAGE_TOO_LARGE: 'BRIDGE_PROTOCOL_MESSAGE_TOO_LARGE',
  BRIDGE_PROTOCOL_UNKNOWN_TYPE: 'BRIDGE_PROTOCOL_UNKNOWN_TYPE',

  BRIDGE_HANDSHAKE_TIMEOUT: 'BRIDGE_HANDSHAKE_TIMEOUT',
  BRIDGE_HANDSHAKE_TOTAL_TIMEOUT: 'BRIDGE_HANDSHAKE_TOTAL_TIMEOUT',
  BRIDGE_HANDSHAKE_USER_MISMATCH: 'BRIDGE_HANDSHAKE_USER_MISMATCH',
  BRIDGE_HANDSHAKE_USER_MISSING: 'BRIDGE_HANDSHAKE_USER_MISSING',
  BRIDGE_HANDSHAKE_BUFFER_OVERFLOW: 'BRIDGE_HANDSHAKE_BUFFER_OVERFLOW',

  BRIDGE_CALL_UNKNOWN_ACTION: 'BRIDGE_CALL_UNKNOWN_ACTION',
  BRIDGE_CALL_ACTION_NOT_SUPPORTED: 'BRIDGE_CALL_ACTION_NOT_SUPPORTED',
  BRIDGE_CALL_ACTION_NOT_AVAILABLE_IN_PHASE: 'BRIDGE_CALL_ACTION_NOT_AVAILABLE_IN_PHASE',
  BRIDGE_CALL_TIMEOUT: 'BRIDGE_CALL_TIMEOUT',
  BRIDGE_CALL_INVALID_PAYLOAD: 'BRIDGE_CALL_INVALID_PAYLOAD',
  BRIDGE_CALL_DUPLICATE_REQUEST_ID: 'BRIDGE_CALL_DUPLICATE_REQUEST_ID',

  BRIDGE_EXEC_ST_INTERNAL: 'BRIDGE_EXEC_ST_INTERNAL',
  BRIDGE_EXEC_TARGET_NOT_FOUND: 'BRIDGE_EXEC_TARGET_NOT_FOUND',
  BRIDGE_EXEC_PRECONDITION_FAILED: 'BRIDGE_EXEC_PRECONDITION_FAILED',
  BRIDGE_EXEC_USER_ACTION_REJECTED: 'BRIDGE_EXEC_USER_ACTION_REJECTED',

  BRIDGE_CONN_IFRAME_UNAVAILABLE: 'BRIDGE_CONN_IFRAME_UNAVAILABLE',
  BRIDGE_CONN_IFRAME_NAVIGATED: 'BRIDGE_CONN_IFRAME_NAVIGATED',
  BRIDGE_CONN_DISCONNECTED: 'BRIDGE_CONN_DISCONNECTED',
} as const;

export type BridgeErrorCode = (typeof BridgeErrorCodes)[keyof typeof BridgeErrorCodes];

const BridgeErrorCodeSchema = z.enum([
  BridgeErrorCodes.BRIDGE_PROTOCOL_VERSION_MISMATCH,
  BridgeErrorCodes.BRIDGE_PROTOCOL_INVALID_ENVELOPE,
  BridgeErrorCodes.BRIDGE_PROTOCOL_PAYLOAD_SCHEMA_INVALID,
  BridgeErrorCodes.BRIDGE_PROTOCOL_MESSAGE_TOO_LARGE,
  BridgeErrorCodes.BRIDGE_PROTOCOL_UNKNOWN_TYPE,
  BridgeErrorCodes.BRIDGE_HANDSHAKE_TIMEOUT,
  BridgeErrorCodes.BRIDGE_HANDSHAKE_TOTAL_TIMEOUT,
  BridgeErrorCodes.BRIDGE_HANDSHAKE_USER_MISMATCH,
  BridgeErrorCodes.BRIDGE_HANDSHAKE_USER_MISSING,
  BridgeErrorCodes.BRIDGE_HANDSHAKE_BUFFER_OVERFLOW,
  BridgeErrorCodes.BRIDGE_CALL_UNKNOWN_ACTION,
  BridgeErrorCodes.BRIDGE_CALL_ACTION_NOT_SUPPORTED,
  BridgeErrorCodes.BRIDGE_CALL_ACTION_NOT_AVAILABLE_IN_PHASE,
  BridgeErrorCodes.BRIDGE_CALL_TIMEOUT,
  BridgeErrorCodes.BRIDGE_CALL_INVALID_PAYLOAD,
  BridgeErrorCodes.BRIDGE_CALL_DUPLICATE_REQUEST_ID,
  BridgeErrorCodes.BRIDGE_EXEC_ST_INTERNAL,
  BridgeErrorCodes.BRIDGE_EXEC_TARGET_NOT_FOUND,
  BridgeErrorCodes.BRIDGE_EXEC_PRECONDITION_FAILED,
  BridgeErrorCodes.BRIDGE_EXEC_USER_ACTION_REJECTED,
  BridgeErrorCodes.BRIDGE_CONN_IFRAME_UNAVAILABLE,
  BridgeErrorCodes.BRIDGE_CONN_IFRAME_NAVIGATED,
  BridgeErrorCodes.BRIDGE_CONN_DISCONNECTED,
]);

export type BridgeErrorPayload = {
  code: BridgeErrorCode;
  message: string;
  requestId?: string;
  context?: Record<string, string | number | boolean>;
};

export const BridgeErrorPayloadSchema = z.object({
  code: BridgeErrorCodeSchema,
  message: z.string(),
  requestId: z.string().optional(),
  context: z.record(z.union([z.string(), z.number(), z.boolean()])).optional(),
});
